M48
; DRILL file {KiCad 9.0.4} date 2025-11-28T16:57:34+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-28T16:57:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X75.055Y-56.8
X80.055Y-56.8
T2
X37.5Y-55.0
X37.5Y-100.0
X107.5Y-55.0
X107.5Y-100.0
M30
